# Generated by Django 5.0.6 on 2024-10-01 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expens_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='spentdata',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
